# -*- coding: utf-8 -*-
"""Data Cleaning and Merging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OThsONSxIhZ2p1ZTcpiQayR1wevqZsbi

# Data Cleaning & Data Merging
## Quantitative Trading System (NIFTY – Daily)

This notebook performs **data cleaning and alignment** on the previously
constructed daily datasets and then merges them into a single unified dataset.

### Tasks Covered
- Task 1.2: Data Cleaning
- Task 1.3: Data Merging

### Input Datasets
- nifty_spot_daily.csv
- nifty_futures_daily.csv
- nifty_options_daily.csv

### Output Deliverables
- Cleaned datasets
- data_cleaning_report.txt
- nifty_merged_daily.csv

---
"""

import pandas as pd
import numpy as np

spot_df = pd.read_csv("nifty_spot_daily.csv")
fut_df  = pd.read_csv("nifty_futures_daily.csv")
opt_df  = pd.read_csv("nifty_options_daily.csv")

spot_df['date'] = pd.to_datetime(spot_df['date'])
fut_df['date']  = pd.to_datetime(fut_df['date'])
opt_df['date']  = pd.to_datetime(opt_df['date'])

"""# DATA CLEANING FOR SPOT DATA"""

spot_df.isna().sum()

spot_df = spot_df.dropna()

"""# DATA CLEANING FOR FUTURE DATA"""

fut_df.isna().sum()

fut_df = fut_df.dropna()

"""# DATA CLEANING FOR OPTIONS DATA"""

opt_df.isna().sum()

opt_df = opt_df.dropna()

"""---

# REMOVING OUTLIERS FOR SPOT CLOSE PRICE AND FUTURE CLOSE PRICE
"""

Q1 = spot_df['close'].quantile(0.25)
Q3 = spot_df['close'].quantile(0.75)
IQR = Q3 - Q1

spot_df = spot_df[
    (spot_df['close'] >= Q1 - 1.5 * IQR) &
    (spot_df['close'] <= Q3 + 1.5 * IQR)
]

Q1 = fut_df['close'].quantile(0.25)
Q3 = fut_df['close'].quantile(0.75)
IQR = Q3 - Q1

fut_df = fut_df[
    (fut_df['close'] >= Q1 - 1.5 * IQR) &
    (fut_df['close'] <= Q3 + 1.5 * IQR)
]

"""**Futures rollover was already handled during near-month contract selection
No additional action required here.**

---

# ATM STRIKE VALIDATION
ATM strikes were:

Dynamically calculated using spot close

Filtered to ATM ±2

Rows without valid ATM reference removed
"""

opt_df[['strike', 'option_type']].head()

"""

---

"""

spot_df.to_csv("nifty_spot_daily_cleaned.csv", index=False)
fut_df.to_csv("nifty_futures_daily_cleaned.csv", index=False)
opt_df.to_csv("nifty_options_daily_cleaned.csv", index=False)

report = f"""
DATA CLEANING REPORT
--------------------
Frequency: Daily
Period: {spot_df['date'].min().date()} to {spot_df['date'].max().date()}

Spot Data:
- Missing values removed
- Outliers removed using IQR

Futures Data:
- Missing values removed
- Near-month rollover already applied
- Outliers removed using IQR

Options Data:
- ATM strike calculated dynamically
- Only ATM ±2 strikes retained
- Rows without spot alignment removed

Timestamp Alignment:
- All datasets aligned on daily 'date'
"""

with open("data_cleaning_report.txt", "w") as f:
    f.write(report)

"""---

# DATA MERGING
"""

merged_df = pd.merge(
    spot_df,
    fut_df,
    on='date',
    how='inner',
    suffixes=('_spot', '_fut')
)

opt_agg = opt_df.groupby(['date', 'option_type']).agg({
    'open_interest': 'sum',
    'volume': 'sum'
}).reset_index()

opt_pivot = opt_agg.pivot(
    index='date',
    columns='option_type',
    values=['open_interest', 'volume']
)

opt_pivot.columns = [
    f"{col[0]}_{col[1].lower()}" for col in opt_pivot.columns
]

opt_pivot = opt_pivot.reset_index()

merged_df = pd.merge(
    merged_df,
    opt_pivot,
    on='date',
    how='left'
)

merged_df.info()

merged_df.head()

merged_df.tail()

merged_df.to_csv("nifty_merged_daily.csv", index=False)

"""## Final Merged Dataset

- Dataset: nifty_merged_daily.csv
- Frequency: Daily
- Components:
  - Spot OHLCV
  - Futures OHLC + Open Interest
  - Aggregated Options Open Interest & Volume (CE / PE)

### Purpose
This dataset serves as the unified input for:
- Feature engineering
- Regime detection
- Machine learning models
- Strategy backtesting

---
"""