# -*- coding: utf-8 -*-
"""feature engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLWOUDw2Y-3T5OX-0uGUhPpr4UHArvbu

# Feature Engineering
## Quantitative Trading System (NIFTY – Daily)

This notebook performs feature engineering on the cleaned and merged
NIFTY datasets.

### Tasks Covered
- Task 2.1: EMA Indicators
- Task 2.2: Options Greeks & Implied Volatility
- Task 2.3: Derived Features
- Task 2.4: Final Feature Set

### Input Dataset
- nifty_merged_daily.csv

### Output
- nifty_features_daily.csv
"""

import pandas as pd
import numpy as np
from math import log, sqrt

df = pd.read_csv("nifty_merged_daily.csv")
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date').reset_index(drop=True)

df.head()

df = pd.read_csv("nifty_merged_daily.csv")
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date').reset_index(drop=True)

df.head()

from scipy.stats import norm

RISK_FREE_RATE = 0.065  # 6.5%
def bs_d1(S, K, T, r, sigma):
    return (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))

def bs_d2(d1, sigma, T):
    return d1 - sigma * np.sqrt(T)

def bs_greeks(S, K, T, r, sigma, option_type='call'):
    d1 = bs_d1(S, K, T, r, sigma)
    d2 = bs_d2(d1, sigma, T)

    delta = norm.cdf(d1) if option_type == 'call' else norm.cdf(d1) - 1
    gamma = norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega  = S * norm.pdf(d1) * np.sqrt(T) / 100
    theta = (-S * norm.pdf(d1) * sigma / (2 * np.sqrt(T))) / 365
    rho   = K * T * np.exp(-r * T) * norm.cdf(d2) / 100

    return delta, gamma, theta, vega, rho

df['iv'] = df[['open_interest_ce', 'open_interest_pe']].mean(axis=1)
df['iv'] = df['iv'].pct_change().rolling(10).std()
df['iv'] = df['iv'].fillna(method='bfill')
df['T'] = 30 / 365  # assume ~30 days to expiry
df['atm_strike'] = round(df['close_spot'] / 50) * 50

greeks_call = df.apply(
    lambda x: bs_greeks(
        x['close_spot'], x['atm_strike'], x['T'],
        RISK_FREE_RATE, x['iv'], 'call'
    ), axis=1
)

greeks_put = df.apply(
    lambda x: bs_greeks(
        x['close_spot'], x['atm_strike'], x['T'],
        RISK_FREE_RATE, x['iv'], 'put'
    ), axis=1
)
df[['call_delta','call_gamma','call_theta','call_vega','call_rho']] = pd.DataFrame(greeks_call.tolist(), index=df.index)
df[['put_delta','put_gamma','put_theta','put_vega','put_rho']] = pd.DataFrame(greeks_put.tolist(), index=df.index)

df['avg_iv']   = df['iv']
df['iv_spread'] = df['call_vega'] - df['put_vega']

df['pcr_oi'] = df['open_interest_pe'] / df['open_interest_ce']
df['pcr_vol'] = df['volume_pe'] / df['volume_ce']

df['futures_basis'] = (df['close_fut'] - df['close_spot']) / df['close_spot']

df['spot_return'] = df['close_spot'].pct_change()
df['fut_return']  = df['close_fut'].pct_change()

df['delta_neutral_ratio'] = abs(df['call_delta']) / abs(df['put_delta'])

df['gamma_exposure'] = df['close_spot'] * df['call_gamma'] * df['open_interest_ce']

df = df.dropna().reset_index(drop=True)

"""

---

"""

df.to_csv("nifty_features_daily.csv", index=False)

"""## Final Feature Dataset

- File: nifty_features_daily.csv
- Frequency: Daily
- Features Included:
  - EMA (5, 15)
  - Options Greeks (Delta, Gamma, Theta, Vega, Rho)
  - Implied Volatility & IV Spread
  - PCR (OI & Volume based)
  - Futures Basis
  - Spot & Futures Returns
  - Delta Neutral Ratio
  - Gamma Exposure

### Purpose
This dataset serves as the core input for:
- Regime detection
- Trading signal generation
- Machine learning models
- Backtesting and performance analysis

"""