# -*- coding: utf-8 -*-
"""Regime Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSTOQZpnY9j7UoqvDKAtmpS7liVKsFDR

# Market Regime Detection using Hidden Markov Models (HMM)
## Quantitative Trading System (NIFTY – Daily)

This notebook implements a **Hidden Markov Model (HMM)** to classify
market conditions into three regimes using **options-based features only**.

### Tasks Covered
- Task 3.1: HMM Implementation
- Task 3.2: Regime Visualization

### Regimes
- Regime +1: Uptrend
- Regime -1: Downtrend
- Regime 0: Sideways

### Input Dataset
- nifty_features_daily.csv

### Output
- Regime labels
- Regime visualizations
"""

import os
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install hmmlearn
from hmmlearn.hmm import GaussianHMM

df = pd.read_csv("nifty_features_daily.csv")
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date').reset_index(drop=True)

df.head()

hmm_features = [
    'avg_iv',
    'iv_spread',
    'pcr_oi',
    'call_delta',
    'call_gamma',
    'call_vega',
    'futures_basis',
    'spot_return'
]

X = df[hmm_features].values

train_size = int(0.7 * len(X))

X_train = X[:train_size]
X_test  = X[train_size:]

MODEL_PATH = "/content/hmm_regime_model.pkl"

if os.path.exists(MODEL_PATH):
    print("✅ Loading existing HMM model...")
    hmm = joblib.load(MODEL_PATH)

else:
    print("🚀 Training new HMM model...")

    train_size = int(0.7 * len(X))
    X_train = X[:train_size]

    hmm = GaussianHMM(
        n_components=3,
        covariance_type="full",
        n_iter=500,
        random_state=42
    )

    hmm.fit(X_train)

    joblib.dump(hmm, MODEL_PATH)
    print(f"💾 HMM model saved to {MODEL_PATH}")

hidden_states = hmm.predict(X)
df['regime_raw'] = hidden_states

state_returns = df.groupby('regime_raw')['spot_return'].mean()
state_returns

regime_map = {
    state_returns.idxmax():  1,   # Uptrend
    state_returns.idxmin(): -1,   # Downtrend
    [s for s in state_returns.index if s not in [state_returns.idxmax(), state_returns.idxmin()]][0]: 0
}

df['regime'] = df['regime_raw'].map(regime_map)

df['regime'].value_counts(normalize=True) * 100

import joblib
joblib.dump(hmm, "hmm_regime_model.pkl")

"""---

# REGIME VISUALIZATION
"""

plt.figure(figsize=(14,6))

colors = {1: 'green', 0: 'blue', -1: 'red'}

for regime in df['regime'].unique():
    subset = df[df['regime'] == regime]
    plt.scatter(
        subset['date'],
        subset['close_spot'],
        color=colors[regime],
        label=f"Regime {regime}",
        s=15
    )

plt.plot(df['date'], df['close_spot'], alpha=0.3)
plt.legend()
plt.title("NIFTY Spot Price with Regime Overlay")
plt.xlabel("Date")
plt.ylabel("Spot Price")
plt.show()

trans_mat = hmm.transmat_

plt.figure(figsize=(5,4))
plt.imshow(trans_mat, cmap='Blues')
plt.colorbar()

plt.title("HMM Regime Transition Matrix")
plt.xlabel("To State")
plt.ylabel("From State")

plt.show()

regime_stats = df.groupby('regime')[[
    'avg_iv',
    'call_delta',
    'call_gamma',
    'call_vega'
]].mean()

regime_stats

df['regime_change'] = df['regime'].ne(df['regime'].shift())
df['regime_group'] = df['regime_change'].cumsum()

durations = df.groupby('regime_group').size()

plt.figure(figsize=(6,4))
plt.hist(durations, bins=20)
plt.title("Regime Duration Histogram")
plt.xlabel("Number of Days")
plt.ylabel("Frequency")
plt.show()

"""## Regime Detection Summary

- Model: Hidden Markov Model (Gaussian)
- States: 3
- Training Data: First 70%
- Features: Options-based + futures basis + spot returns

### Identified Regimes
- +1: Uptrend (positive average returns)
- -1: Downtrend (negative average returns)
- 0: Sideways (low return magnitude)

### Usage in Trading System
- Regime-aware strategy selection
- Risk management and position sizing
- Filtering false signals in sideways markets

---
"""

df[['date', 'regime']].to_csv("nifty_regimes_daily.csv", index=False)